version: '3'

services:
  app:
    image: marcelloale/go-api-mongo
    ports:
      - 9080:9080
    environment:
      MONGO_DB_HOST: mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
